Adding Annual Meeting Slides

diff --git a/push_update b/push_update
--- a/push_update
+++ b/push_update
@@ -1,4 +1,21 @@
 #!/bin/zsh
+
+# Iterate over all files in the current directory
+#  4 for file in *; do
+#  5   # Check if it's a regular file
+#  6   if [[ -f "$file" ]]; then
+#  7     # Get the file size in bytes
+#  8     eval $(/usr/bin/stat -s "$file")
+#  9     echo "size: " $st_size
+# 10
+# 11     # Check if the file size exceeds 100 MB (100 * 1024 * 1024 bytes)
+# 12     if (( $st_size > 100 * 1024 * 1024 )); then
+# 13       echo "Error: File '$file' exceeds 100 MB." >&2
+# 14       exit 1
+# 15     fi
+# 16   fi
+# 17 done
+
 git add --all
 git commit -m "$1"
 git push -u origin main
